### ISSUE TITLE
FPDF error: 16-bit depth not supported

### ISSUE THREAD

**Issue by The-Johnson** [DiddiZ/mtg-proxies#15]
I'm getting this issue while trying to export a decklist. 

RuntimeError: FPDF error: 16-bit depth not supported: /var/folders/g4/8203zyrj6jsbpj2dw625y1xh0000gn/T/scryfall_cache/png_front_73b58a5d-1eed-41ca-a2ea-d17763e7e22d.png 

It seems to be always getting to card 30 while plotting, but I changed the printing in the decklist, I even moved it to position 31 to see if it would make any difference, but no luck, still errors out on card 30 during plotting. 

EDIT1: I was able to identify the problematic card. Ghost Quarter - Secret Lair Drop - SLD(468)
The card may indeed be 16-bit, but why would that be a problem?

**Comment by DiddiZ** [comment]
I'm not able to reproduce this. While the art of Ghost Quarter indeed has 16 bit per channel, printing it does work,

Maybe this was fixed meanwhile in fpdf.
