### ISSUE TITLE
Is there supposed to be a Pipfile in this repository?

### ISSUE THREAD

**Issue by clarle** [DiddiZ/mtg-proxies#16]
I'm trying to install it but there's no Pipfile to run pipenv with.  I was able to bypass it because I see what requirements are needed in the setup.py file, but I think the Pipfile should be checked in.

**Comment by clarle** [comment]
I was able to run it the old-school way with:
```bash
python setup.py install
python print.py examples/decklist.txt decklist.pdf
```
But yeah, I don't think you can run it with pipenv if we don't have the Pipfile.

**Comment by DiddiZ** [comment]
Yes, sorry about that. I was moving away from pipenv and forgot to update the README.
