### ISSUE TITLE
Frustration with Dual Faced Cards 

### ISSUE THREAD

**Issue by Ms-Rabbit** [DiddiZ/mtg-proxies#18]
I wish there was a way to have the backside of DFCs be appended to the end of the pdf, or added to a second pdf instead. 
This would be helpful when printing proxies on cardstock, to separately print the backsides on regular paper and then glue them to the cardstock back

Thank you for the wonderful tool

**Comment by DiddiZ** [comment]
Thans for your suggestion. You can now use the `--face` CLI argument to print front or back sides separately.
