### ISSUE TITLE
Choose background color

### ISSUE THREAD

**Issue by GregorKobsik** [DiddiZ/mtg-proxies#3]
The background color is always white (default setting)

It would be nice to have an option to choose an arbitary color for the background.

e.g.

**human readable input:**
`python print.py --background "black" examples/decklist.txt decklist.pdf
`
**rgb-valued input:**
`python print.py --background (200,200,200) examples/decklist.txt decklist.pdf`

**Comment by DiddiZ** [comment]
Use 
`python print.py --background black examples/decklist.txt decklist.pdf`
or
`python print.py --background "#c8c8c8" examples/decklist.txt decklist.pdf`
