### ISSUE TITLE
Missing scaling of the card size

### ISSUE THREAD

**Issue by GregorKobsik** [DiddiZ/mtg-proxies#4]
Some output deviced rescale the input image and therefore the print file needs to be rescaled accordingly. 
Some print devices even upscale the image and crop it later to the correct size.

An argument (-scale), which allows to counteract this behaviour would be very handy.
The programm rescales the image relative to the output size, while remaining the desired output size of the image.

Input as total value:
`python print.py -scale 95 examples/decklist.txt decklist.pdf`
The resulting image will be rescaled to 95% of its original size

Input as relative value
`python print.py -scale +3 examples/decklist.txt decklist.pdf`
The resulting image will be rescaled to 103% of its original size

`python print.py -scale -7 examples/decklist.txt decklist.pdf`
The resulting image will be rescaled to 93% of its original size

**Comment by DiddiZ** [comment]
Use 
`python print.py --scale 0.95 examples/decklist.txt decklist.pdf`
`python print.py --scale 1.03 examples/decklist.txt decklist.pdf`
`python print.py --scale 0.93 examples/decklist.txt decklist.pdf`
for 95% (resp 103%, 93%) of its original size.
